export const FOLLOWERS_LIST_REQUEST = 'FOLLOWERS_LIST_REQUEST'
export const FOLLOWERS_LIST_SUCCESS = 'FOLLOWERS_LIST_SUCCESS'
export const FOLLOWERS_LIST_FAIL = 'FOLLOWERS_LIST_FAIL'

export const FOLLOWER_ADD_REQUEST = 'FOLLOWER_ADD_REQUEST'
export const FOLLOWER_ADD_SUCCESS = 'FOLLOWER_ADD_SUCCESS'
export const FOLLOWER_ADD_FAIL = 'FOLLOWER_ADD_FAIL'

export const FOLLOWER_REMOVE_REQUEST = 'FOLLOWER_REMOVE_REQUEST'
export const FOLLOWER_REMOVE_SUCCESS = 'FOLLOWER_REMOVE_SUCCESS'
export const FOLLOWER_REMOVE_FAIL = 'FOLLOWER_REMOVE_FAIL'