export const FOLLOWERS_LIST_REQUEST = 'FOLLOWERS_LIST_REQUEST'
export const FOLLOWERS_LIST_SUCCESS = 'FOLLOWERS_LIST_SUCCESS'
export const FOLLOWERS_LIST_FAIL = 'FOLLOWERS_LIST_FAIL'

export const FOLLOWER_REMOVE_REQUEST = 'FOLLOWER_REMOVE_REQUEST'
export const FOLLOWER_REMOVE_SUCCESS = 'FOLLOWER_REMOVE_SUCCESS'
export const FOLLOWER_REMOVE_FAIL = 'FOLLOWER_REMOVE_FAIL'

export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST'
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL'

export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST'
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS'
export const UNFOLLOW_USER_FAIL = 'UNFOLLOW_USER_FAIL'
