export const SUBMIT_REVIEW_REQUEST = 'SUBMIT_REVIEW_REQUEST'
export const SUBMIT_REVIEW_SUCCESS = 'SUBMIT_REVIEW_SUCCESS'
export const SUBMIT_REVIEW_FAILURE = 'SUBMIT_REVIEW_FAILURE'

export const FETCH_USER_REVIEWS_REQUEST = 'FETCH_USER_REVIEWS_REQUEST'
export const FETCH_USER_REVIEWS_SUCCESS = 'FETCH_USER_REVIEWS_SUCCESS'
export const FETCH_USER_REVIEWS_FAILURE = 'FETCH_USER_REVIEWS_FAILURE'