export const FETCH_USER_DETAILS_REQUEST = 'FETCH_USER_DETAILS_REQUEST'
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS'
export const FETCH_USER_DETAILS_FAILURE = 'FETCH_USER_DETAILS_FAILURE'

export const FETCH_USER_ARTICLES_REQUEST = 'FETCH_USER_ARTICLES_REQUEST'
export const FETCH_USER_ARTICLES_SUCCESS = 'FETCH_USER_ARTICLES_SUCCESS'
export const FETCH_USER_ARTICLES_FAILURE = 'FETCH_USER_ARTICLES_FAILURE'

export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS_REQUEST'
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS'
export const UPDATE_USER_DETAILS_FAILURE = 'UPDATE_USER_DETAILS_FAILURE'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'

export const FETCH_STRANGER_DETAILS_REQUEST = 'FETCH_STRANGER_DETAILS_REQUEST'
export const FETCH_STRANGER_DETAILS_SUCCESS = 'FETCH_STRANGER_DETAILS_SUCCESS'
export const FETCH_STRANGER_DETAILS_FAILURE = 'FETCH_STRANGER_DETAILS_FAILURE'

export const FETCH_STRANGER_ARTICLES_REQUEST = 'FETCH_STRANGER_ARTICLES_REQUEST'
export const FETCH_STRANGER_ARTICLES_SUCCESS = 'FETCH_STRANGER_ARTICLES_SUCCESS'
export const FETCH_STRANGER_ARTICLES_FAILURE = 'FETCH_STRANGER_ARTICLES_FAILURE'