name: CI

on:
  push:
    branches:
      - main  # Ändere dies entsprechend deiner Hauptbranch-Bezeichnung

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Verwende die neueste stabile Node.js-Version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test -- --coverage
