name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: yabe-project
          password: yabe-project
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: 12evba1biff/testjodejsapp
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Start Docker container for testing
        run: |
          docker run -d --name test-container ${{ steps.meta.outputs.tags }}
          sleep 10
          docker ps | grep test-container
      
      - name: Check if container is running
        run: |
          if [[ $(docker ps | grep test-container) ]]; then
            echo "Container is running"
          else
            echo "Container is not running"
            exit 1
          fi
