# .github/workflows/main.yml

name: CI

on:
  push:
    branches:
      - main  # Ändere dies entsprechend deiner Hauptbranch-Bezeichnung

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build and push Docker image
      run: |
        docker build -t my-react-app .
        docker tag my-react-app:latest docker.pkg.github.com/${{ github.repository }}/my-react-app:latest
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        docker push docker.pkg.github.com/${{ github.repository }}/my-react-app:latest
